name: Safety Gate

on:
  pull_request:

jobs:
  safety:
    runs-on: ubuntu-latest
    env:
      ROBOT_RUN_BASE: ${{ runner.temp }}/runs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run safety edge case
        run: python -m simulation.run_case --case safety_edge --dry-run
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safety-gate-artifacts
          path: ${{ env.ROBOT_RUN_BASE }}
